[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.1.4"

[[constraint]]
  name = "vbom.ml/util"
  revision = "256737ac55c46798123f754ab7d2c784e2c71783"
