[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "=v1.1.0"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "=v1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "=v1.1.4"
